language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install

# Travis caching
cache:
	directories:
		- node_modules

#before_script:
	# - npm install -g gulp

script:
	- hexo g

after_script:
	- cd ./public
  - git init
	- git config user.name "marzlia"
  - git config user.email "marzlia@qq.com"
	- git add .
	- git commit -m "Update docs"
	- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
	# E: Build LifeCycle

#build branch
branches:
  only:
	  - master

#build env		
env:
	global:
	  - GH_REF: github.com/marzlia/marzlia.github.io.git
